# Unfogified manual deployment

version: "3.7"

services:
  generator:
    image: generator1
    environment:
      - INTERVAL=1
      - AGGREGATOR=aggregator1
      - PORT=5000
    depends_on:
      - aggregator1

  generator_2:
    image: generator2
    environment:
      - INTERVAL=1
      - AGGREGATOR=aggregator
      - PORT=5000
      - LOCATION=Barcha
      - ID=2
    depends_on:
      - aggregator

  aggregator:
    image: aggregator1
    environment:
      - PROCESSOR_PORT=5003
      - PROCESSOR=processor
      - PORT=5000
    ports:
      - 5000
    depends_on:
      - processor1

  processor:
    image: processor1
    environment:
      - PORT=5003
    ports:
      - 5003
