services:
  aggregator_0_service:
    environment:
    - PROCESSOR=processor_0_item
    - PROCESSOR_PORT=5003
    - PORT=5002
    - ID=0
    - WINDOW=10
    - BUSY_WAIT=1000000
    image: aggregator
    ports:
    - 5002
  generator_0_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=0
    image: generator
  generator_1_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=1
    image: generator
  generator_2_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=2
    image: generator
  generator_3_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=3
    image: generator
  generator_4_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=4
    image: generator
  generator_5_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=5
    image: generator
  generator_6_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=6
    image: generator
  generator_7_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=7
    image: generator
  generator_8_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=8
    image: generator
  generator_9_service:
    environment:
    - INTERVAL=0.1
    - AGGREGATOR=aggregator_0_item
    - PORT=5002
    - LOCATION=Floor1
    - ID=9
    image: generator
  processor_0_service:
    environment:
    - HISTORY_LENGTH=10
    - PORT=5003
    - ID=0
    image: processor
    ports:
    - 5005:5003
version: '3.7'
x-fogify:
  networks:
  - downlink:
      bandwidth: 5Mbps
      latency:
        delay: 50ms
    links:
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 3.79ms
      to_node: aggregator_0_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 11.72ms
      to_node: generator_0_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 3.89ms
      to_node: generator_1_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 6.59ms
      to_node: generator_2_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 8.53ms
      to_node: generator_3_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 6.7ms
      to_node: generator_4_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 4.3ms
      to_node: generator_5_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 9.92ms
      to_node: generator_6_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 6.45ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 4.2ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: processor_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 3.95ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 9.64ms
      to_node: generator_0_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 15.23ms
      to_node: generator_1_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 8.57ms
      to_node: generator_2_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 13.95ms
      to_node: generator_3_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 9.57ms
      to_node: generator_4_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 8.51ms
      to_node: generator_5_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 11.67ms
      to_node: generator_6_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 12.98ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 10.6ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: aggregator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 28.36ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 7.57ms
      to_node: generator_1_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 7.41ms
      to_node: generator_2_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 6.19ms
      to_node: generator_3_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 22.96ms
      to_node: generator_4_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 17.25ms
      to_node: generator_5_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 11.37ms
      to_node: generator_6_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 15.68ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 15.19ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: generator_0_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 7.97ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_1_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 12.23ms
      to_node: generator_2_item
    - bidirectional: true
      from_node: generator_1_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 6.43ms
      to_node: generator_3_item
    - bidirectional: true
      from_node: generator_1_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 11.73ms
      to_node: generator_4_item
    - bidirectional: true
      from_node: generator_1_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 9.39ms
      to_node: generator_5_item
    - bidirectional: true
      from_node: generator_1_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 5.39ms
      to_node: generator_6_item
    - bidirectional: true
      from_node: generator_1_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 6.32ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: generator_1_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 13.13ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: generator_1_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 11.66ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_2_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 10.03ms
      to_node: generator_3_item
    - bidirectional: true
      from_node: generator_2_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 7.72ms
      to_node: generator_4_item
    - bidirectional: true
      from_node: generator_2_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 4.7ms
      to_node: generator_5_item
    - bidirectional: true
      from_node: generator_2_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 15.68ms
      to_node: generator_6_item
    - bidirectional: true
      from_node: generator_2_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 9.69ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: generator_2_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 16.95ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: generator_2_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 7.07ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_3_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 7.95ms
      to_node: generator_4_item
    - bidirectional: true
      from_node: generator_3_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 4.84ms
      to_node: generator_5_item
    - bidirectional: true
      from_node: generator_3_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 9.42ms
      to_node: generator_6_item
    - bidirectional: true
      from_node: generator_3_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 10.96ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: generator_3_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 6.91ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: generator_3_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 4.95ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_4_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 11.47ms
      to_node: generator_5_item
    - bidirectional: true
      from_node: generator_4_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 6.36ms
      to_node: generator_6_item
    - bidirectional: true
      from_node: generator_4_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 13.03ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: generator_4_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 13.49ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: generator_4_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 7.11ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_5_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 5.83ms
      to_node: generator_6_item
    - bidirectional: true
      from_node: generator_5_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 26.1ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: generator_5_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 9.52ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: generator_5_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 8.11ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_6_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 14.43ms
      to_node: generator_7_item
    - bidirectional: true
      from_node: generator_6_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 12.47ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: generator_6_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 16.0ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_7_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 9.93ms
      to_node: generator_8_item
    - bidirectional: true
      from_node: generator_7_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 7.14ms
      to_node: generator_9_item
    - bidirectional: true
      from_node: generator_8_item
      properties:
        bandwidth: 1000Mbps
        latency:
          delay: 13.86ms
      to_node: generator_9_item
    name: internet
    uplink:
      bandwidth: 10Mbps
      latency:
        delay: 50ms
  nodes:
  - capabilities:
      memory: 256.000M
      processor:
        clock_speed: 100
        cores: 2
    name: processor_0_node
  - capabilities:
      memory: 256.000M
      processor:
        clock_speed: 100
        cores: 1
    name: aggregator_0_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_0_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_1_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_2_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_3_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_4_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_5_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_6_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_7_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_8_node
  - capabilities:
      memory: 128.000M
      processor:
        clock_speed: 100
        cores: 1
    name: generator_9_node
  topology:
  - label: processor_0_item
    networks:
    - internet
    node: processor_0_node
    replicas: 1
    service: processor_0_service
  - label: aggregator_0_item
    networks:
    - internet
    node: aggregator_0_node
    replicas: 1
    service: aggregator_0_service
  - label: generator_0_item
    networks:
    - internet
    node: generator_0_node
    replicas: 1
    service: generator_0_service
  - label: generator_1_item
    networks:
    - internet
    node: generator_1_node
    replicas: 1
    service: generator_1_service
  - label: generator_2_item
    networks:
    - internet
    node: generator_2_node
    replicas: 1
    service: generator_2_service
  - label: generator_3_item
    networks:
    - internet
    node: generator_3_node
    replicas: 1
    service: generator_3_service
  - label: generator_4_item
    networks:
    - internet
    node: generator_4_node
    replicas: 1
    service: generator_4_service
  - label: generator_5_item
    networks:
    - internet
    node: generator_5_node
    replicas: 1
    service: generator_5_service
  - label: generator_6_item
    networks:
    - internet
    node: generator_6_node
    replicas: 1
    service: generator_6_service
  - label: generator_7_item
    networks:
    - internet
    node: generator_7_node
    replicas: 1
    service: generator_7_service
  - label: generator_8_item
    networks:
    - internet
    node: generator_8_node
    replicas: 1
    service: generator_8_service
  - label: generator_9_item
    networks:
    - internet
    node: generator_9_node
    replicas: 1
    service: generator_9_service
