generator:
  image: generator
  environment:
    - ID=get_node_id()
    - INTERVAL=1
    - AGGREGATOR=get_parent_node()
    - PORT=5002

aggregator:
  image: aggregator
  environment:
    - ID=[[2]]
    - PROCESSOR_PORT=5003
    - PROCESSOR=[[processor]]
    - PORT=5002
  ports:
    - "5000:5002"

processor:
  image: processor
  environment:
    - PORT=5003
  ports:
    - "5001:5003"
